# Generated by Django 6.0.3 on 2026-03-20 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['date', 'created_at']},
        ),
    ]
